[phases.setup]
    nixPkgs = ['nodejs', 'python3']
    aptPkgs = ['build-essential', 'libudev-dev']

[phases.install]
    cmds = [
        'npm install -g pnpm@10.6.1',
        'pnpm install'
    ]

[phases.build]
    cmds = ['pnpm run build']

[phases.start]
    cmd = 'pnpm run pm2'